### ISSUE TITLE
Add support for resource actions

### ISSUE THREAD

**Issue by mathiasjakobsen** [stonecircle/redux-json-api#141]
As discussed in https://github.com/json-api/json-api/issues/320, the `JSON:API` standard lacks a specification on how resource actions should be handled. Until it's settled I propose that `redux-json-api` implements a `writeEndpoint` actionCreator similar to `readEndpoint` but as a POST request, which makes it up to the developer how to handle the semantics regarding resource actions.

I argue that this should be implemented, so that developers do not have to setup another client with headers, authentication, etc. when the `redux-json-api` client is already present.

**Comment by egeriis** [comment]
That's a super interesting discussion. One that hasn't even been solved—as far as I am aware—by REST.

We are super open to PRs implementing some way of achieving this.

In our own use cases, we used magic resource attributes that would trigger an action. E.g.

```
{
  "id": 1,
  "type": "users",
  "attributes": {
    "invite": true
  }
}
```

**Comment by egeriis** [comment]
I missed that you already made a PR, awesome. I'll take a look.
