### ISSUE TITLE
Clear state

### ISSUE THREAD

**Issue by chrisjowen** [stonecircle/redux-json-api#24]
Hey Guys, 

Whenever I make a request to readEndpoint it updates my state as I expected, but there are times when I really don't want to keep storing all this info in state and adding to it every time. One example of this in my case is a search functionality, every time I search I increase the amount of info in the state and I really want to simply replace what was there with the response from the last read. 

It would be nice to have if the readEndpoint action creator took some options one of which been to replace or concat the results like:

`readEndpoint("/search/foo", { clear: true })`

This is just an example and that might be quite an ugly api and you can think of a better approach. Alternatively, is there a way to extend your reducer so I can do this manually? 

Chris

**Comment by egeriis** [comment]
Hey @chrisjowen,

It's quite simple to extend the reducer using [reduce-reducers](https://github.com/acdlite/reduce-reducers).

Example: 

```js
import { reducer } from 'redux-json-api';

export default reduceReducers(
  reducer,
  handleAction(CLEAR_SEARCH, ({ isCreating, isReading, isUpdating, isDeleting, endpoint }) => ({
    isCreating, 
    isReading, 
    isUpdating, 
    isDeleting, 
    endpoint
  }))
);
```

**Comment by egeriis** [comment]
We did consider adding an ability to clear a certain key on the API state, as you're suggesting. It's not something we've prioritized yet, or even considered which use cases should be covered.

A concern I have with your example, is that "/search/foo" is not a RESTful endpoint. It should be something like: "/users?filter[name]=foo" or "/search?filter[any]=foo". The `filter` param is very flexible in terms of the JSON API spec.

**Comment by chrisjowen** [comment]
I agree this is not as per JSON api spec (its still RESTfull though :p) but really its besides the point, a search is a good example where you would not likely want to keep all the state whatever way it is performed. 

Im sure there must be many more use cases, for sure not all things that are returned from a rest call want to be kept on the client for longer than they are required. In the end I did actually just wrapped your reducer and added the functionality I needed, though I had to duplicate your initial state so it might be nice if you could export that.

**Comment by egeriis** [comment]
Yup, I agree that there may be more use cases. Make sure to let us know if you come up with any other cases. And search is a good use case, absolutely.

One of the challenges that are not straight forward to solve, is the challenge of which namespace in the API state should be cleared, when performing _this_ request. E.g., doing:

```js
readEndpoint('/users?filter[name]=foo', { clear: true })
```

Which namespace is cleared? Or will the entire API state be reset? 

An approach to this problem could be for the user to specify which namespace to clear:

```js
readEndpoint('/users?filter[name]=foo', { clear: 'users' })
```

I am not sure about this solution, as it may clear entities that you would want to keep.

**Comment by Nopzen** [comment]
Extending to your two possible solutions @egeriis, i think that it would be clear for the user what we clear with this approch:

```javascript
readEndpoint('/users?filter[name]=foo', { clear: true })
```
Due to the nature of the tool, that what we query, we will store on a certain type key, if we just pass a options object `{ clear: true }` it should clear that key it would be stored in, and also limit the amount of options that needs to be passed, various constants and so forth. 

So i do like this idea more than `{ clear: 'explicitName' }`

Another approach i guess could be adding a clearKeyState('keyName'), that would just clear that specific key of data and make it return an empty array. This could then be utilized as a user would see fit.

**Comment by chrisjowen** [comment]
For what its worth for my use case I simply went for the explicit `clearState('keyName')` approach.

@Nopzen Im not sure that this is so clear, in my mind there are two ways of reading:

`readEndpoint('/users?filter[name]=foo', { clear: true })`

One is that the users key will be cleared, the other is that only users with the name 'foo' will be cleared from the collection in the key. 

It gets even more confusing when talking about includes and sparse field sets, for example what would you clear here:

`readEndpoint('/users?filter[name]=foo&include=comments&fields[comment]=title,body', { clear: true })`

**Comment by egeriis** [comment]
@chrisjowen That's some of my concern too. Also considering the nature of this library, that we're essentially grouping all entities of same type within the same key, will make it hard to solve this problem in a right way. So let's keep this discussion going :)

`clearEntities('users')` makes sense, it's easy to read and comprehend. However, it clears the entire list of `users` entities—as far as how I see this being implemented.

`readEndpoint('/users?filter[name]=foo', { clear: true })` is useful, considering that it's only necessary to dispatch a single action in the application layer. It is not easy to comprehend, as you point out Chris, which entities are cleared. 

Another pitfall is something like `readEndpoint('/users/1/comments', { clear: true })`. Does this clear users or comments? To me, it's obviously comments, but I imagine that it's not obvious to others.

**Comment by chrisjowen** [comment]
@egeriis  to me that would read that its clearing the comments only related to user/1. I think this might get complicated quickly, maybe just adding a better way to extend your reducer without having to copy the default parameters would be all that is required. I still also think that the generic ```clearEntities('users')``` makes a lot of sense, and yeah I would also assume it clear everything there

**Comment by egeriis** [comment]
So maybe the approach of adding another action creator, `clearEntities`, is the way to go. I think this is the most clear solution too. It _could_ have a second argument with a callback, that would act as a filter. It could work as `Array.prototype.filter` to tell the library which entities to reject and keep.

**Comment by gazpachu** [comment]
@egeriis Thanks for pointing me at this discussion. I don't know where I can put the code you posted in the 2nd message. I guess it has to go in a different file from my component, otherwise I get `Module build failed: SyntaxError: Only one default export allowed per module.`.

Would it be possible for you to extend the example to cover a single scenario where we need to clear one specific resource that was previously read?

Thanks

**Comment by egeriis** [comment]
The reducer example I posted should be put in a `api` module. I don't know your file structure, so I cannot tell you where to place that file. Then you can import this module instead of the reducer from _redux-json-api_, as that's the one we're extending here.

1. Create a new reducer with above snippet
1. Import this, instead of `reducer` from _redux-json-api_ where you're combining your reducers
1. Profit

**Comment by gazpachu** [comment]
thanks @egeriis, I'm not sure I'm doing it correctly :-S

I get error `Uncaught TypeError: (0 , _reduceReducers.handleAction) is not a function` and if I don't import `handleAction`, I get `Uncaught ReferenceError: handleAction is not defined`. What am I doing wrong?

```
import { reducer } from 'redux-json-api';
import { reduceReducers, handleAction, CLEAR_SEARCH } from 'reduce-reducers';

export default reduceReducers(
	reducer,
	handleAction(CLEAR_SEARCH, ({ isCreating, isReading, isUpdating, isDeleting, endpoint }) => ({
		isCreating, 
		isReading, 
		isUpdating, 
		isDeleting, 
		endpoint
	}))
);
```

**Comment by egeriis** [comment]
You don't need to use the same convention as _redux-actions_ (which exposed `handleAction`). Simply pass your reducer to `reduceReducers`:

```js
const api = reduceReducers(
  reducer,
  ({ isCreating, isReading, isUpdating, isDeleting, endpoint }, action) => {
    if (action.type !== RESET_RESOURCE) {
      return state;
    }

    return {
      isCreating, 
      isReading, 
      isUpdating, 
      isDeleting, 
      endpoint
    };
  }
);
```

Something like that should do.

**Comment by gazpachu** [comment]
`state` is not defined. Where shall I put it?

So, with this example, I would only have to call my action to trigger RESET_RESOURCE and that should clear the resources that my readEndpoint will get?

```
export function resetResource(type, state) {
	return {
		type: 'RESET_RESOURCE',
		payload: state
	}
}
```

**Comment by egeriis** [comment]
Oh, sorry @gazpachu. The destructuring in the function is from state. You should be able to replace that.

**Comment by gazpachu** [comment]
Hi @egeriis. Sorry for asking so many questions. I'm not very good at this :( My apologies but, I still don't know what you mean or how to fix this issue.

**Comment by egeriis** [comment]
About destructuring https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

Read up on that, and see if that helps you understand :)

**Comment by gazpachu** [comment]
Thanks for the destructuring article. I've figured out that it should be:

```
const api = reduceReducers(
  	reducer,
  	(state, action) => {
```

Now it seems it cannot find `isCreating` and the other flags, so I've tried to import them:

`import { reducer, isCreating, isReading, isUpdating, isDeleting, endpoint } from 'redux-json-api';`

but that doesn't seem to work. It seems they are not being exported in `https://github.com/dixieio/redux-json-api/blob/master/src/jsonapi.js`?

**Comment by gazpachu** [comment]
Unless, it's this other way:

```
const api = reduceReducers(
  	reducer,
  	({isCreating, isReading, isUpdating, isDeleting, endpoint}, action) => (state, action) => {
```

In which case, I get:

`jsonapi.js Uncaught TypeError: Cannot read property 'host' of undefined`, which I guess it comes from endpoint being undefined

**Comment by egeriis** [comment]
They're not flags, they're properties on `state`. 

The reducer should clear entities from state when the RESET_RESOURCE action is dispatched, i.e `action.type === RESET_RESOURCE`.

But it shouldn't clear the key properties from state, which is `isCreating`, `isReading`, `isUpdating`, `isDeleting` and `endpoint`.

Thus we need a reducer that checks on the dispatched action type and returns the value expected from above logic.

```js
(state, action) => {
  // if the action type is _not_ RESET_RESOURCE, no action taken
  if (action.type !== RESET_RESOURCE) {
    return state;
  }
  // if the action type _is_ RESET_RESOURCE, clear everything but key attributes from state
  const { isCreating, isReading, isUpdating, isDeleting, endpoint } = state;
  return {
    isCreating, isReading, isUpdating, isDeleting, endpoint
  };
}
```

**Comment by gazpachu** [comment]
ok, this works. But this approach resets the whole app state. Not just the state of the specific resource that I'm reading again.

**Comment by gazpachu** [comment]
This works, thanks a lot! I'll figure out how to do it to reset just the resource I want to read again.

You are a star! :)

**Comment by gazpachu** [comment]
What would be the best way to remove a resource of type `answers` from the state?

I've tried two methods that remove the data from the resource, but on the next readEndpoint call still adds up the new data and the old data :/

Method 1:
```
// if the action type _is_ RESET_RESOURCE, get everything from the state except the resource we want to reset
if (action.payload === 'answers') {
       return Object.assign({}, state, {answers: {}});
}
```

Method 2:
```
// if the action type _is_ RESET_RESOURCE, get everything from the state except the resource we want to reset
if (action.payload === 'answers') {
       // Recommended here: http://stackoverflow.com/questions/33053310/remove-value-from-object-without-mutating-it
       let res = Object.assign({}, state});
       delete res.answers;
       return res;
}
```

**Comment by egeriis** [comment]
Do you have Redux DevTools? Can you verify that they're actually removed from state?

**Comment by gazpachu** [comment]
Yes, everything works fine now. I had a bug somewhere else that was calling twice the readEndpoint (long sigh... + face palm)

**Comment by egeriis** [comment]
Cool :)
